name: pkgcheck
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master
      - develop


env:
  SNOMEDIZER_ENDPOINT: https://snowstorm.test-nictiz.nl/

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
